spring:
  datasource:
      url: jdbc:mysql://localhost:3306/homeschool?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: tang3255332
mybatis:
   mapperLocations: classpath:/mapper/*.xml
